export const years = [
  "2023",
  "2022",
  "2021",
  "2020",
  "2019",
  "2018",
  "2017",
  "2016",
  "2015",
  "2014",
  "2013",
  "2012",
  "2011",
  "2010",
  "2009",
  "2008",
  "2007",
  "2006",
  "2005",
  "2004",
  "2003",
  "2002",
  "2001",
  "2000",
  "1999",
  "1998",
  "1997",
  "1996",
  "1995",
  "1994",
  "1993",
  "1992",
  "1991",
  "1990",
  "1989",
  "1988",
  "1987",
  "1986",
  "1985",
  "1984",
  "1983",
  "1982",
  "1981",
  "1980",
  "1979",
  "1978",
  "1977",
  "1976",
  "1975",
  "1974",
  "1973",
  "1972",
  "1971",
  "1970",
  "1969",
  "1968",
  "1967",
  "1966",
  "1965",
  "1964",
  "1963",
  "1962",
  "1961",
  "1960",
]

export const medicalCouncil = [
  "Andhra Pradesh Medical Council",
  "Arunachal Pradesh Medical Council",
  "Assam Medical Council",
  "Bhopal Medical Council",
  "Bihar Medical Council",
  "Bombay Medical Council",
  "Chandigarh Medical Council",
  "Chattisgarh Medical Council",
  "Delhi Medical Council",
  "Goa Medical Council",
  "Gujarat Medical Council",
  "Haryana Medical Councils",
  "Himachal Pradesh Medical Council",
  "Hyderabad Medical Council",
  "Jammu & Kashmir Medical Council",
  "Jharkhand Medical Council",
  "Karnataka Medical Council",
  "Madhya Pradesh Medical Council",
  "Madras Medical Council",
  "Mahakoshal Medical Council",
  "Maharashtra Medical Council",
  "Manipur Medical Council",
  "Medical Council of India",
  "Medical Council of Tanganyika",
  "Mizoram Medical Council",
  "Mysore Medical Council",
  "Nagaland Medical Council",
  "Orissa Council of Medical Registration",
  "Pondicherry Medical Council",
  "Punjab Medical Council",
  "Rajasthan Medical Council",
  "Sikkim Medical Council",
  "Tamil Nadu Medical Council",
  "Telangana State Medical Council",
  "Travancore Cochin Medical Council, Trivandrum",
  "Tripura State Medical Council",
  "Uttar Pradesh Medical Council",
  "Uttarakhand Medical Council",
  "Vidharba Medical Council",
  "West Bengal Medical Council",
  "Others"
]

export const degree = [
  "MBBS",
  "MS",
  "MD",
  "BDS",
  "MDS",
  "BAMS",
  "Others"
]

export const states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Mehalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajastan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
  "Andaman and Nicobar",
  "Chandigarh",
  "Dadra and Nagar Haveli",
  "Delhi(NCT)",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshwadeep",
  "Puducherry",
]

export const medicalCouncilOptions = {
  "Allopathy": [
    "Andhra Pradesh Medical Council",
    "Arunachal Pradesh Medical Council",
    "Assam Council of Medical Registration",
    "Bihar Medical Council",
    "CHD Medical Council",
    "Chhattisgarh Medical Council",
    "Delhi Medical Council",
    "Goa Medical Council",
    "Gujarat Medical Council",
    "Haryana Medical Council",
    "Himanchal Pradesh Medical Council",
    "Jammu and Kashmir Medical Council",
    "Jharkhand Medical Council",
    "Karnataka Medical Council",
    "Kerala State Medical Councils",
    "Madhya Pradesh Medical Council(Bhopal Medical Council / Mahakaushal Medical Council)",
    "Maharashtra Medical Council",
    "Manipur Medical Council",
    "State Medical Council, Meghalaya",
    "Mizoram Medical Council",
    "Nagaland Medical Council",
    "Orissa Council of Medical Registration",
    "Punjab Medical Council",
    "Rajasthan Medical Council",
    "Sikkim Medical Council",
    "Tamil Nadu Medical Council",
    "Telangana State Medical Council",
    "Tripura State Medical Council",
    "Uttarakhand Medical Council",
    "Uttar Pradesh Medical Council",
    "West Bengal Medical Council",
    "National Medical Commission(erstwhile Medical Council of India)"
  ],
  "Dentistry": [
    "Andhra Pradesh State Dental Council",
    "Arunachal Pradesh State Dental Council",
    "Assam State Dental Council",
    "Bihar State Dental Council",
    "Dental Council of Chandigarh",
    "Chhattisgarh State Dental Council",
    "Delhi State Dental Council",
    "Goa State Dental Council",
    "Gujarat State Dental Council",
    "Haryana State Dental Council",
    "Himachal Pradesh State Dental Council",
    "Jammu and Kashmir State Dental Council",
    "Jharkhand State Dental",
    "Council Karnataka State Dental Council",
    "Kerala Dental Council",
    "Madhya Pradesh State Dental Council",
    "Maharashtra State Dental Council",
    "Manipur State Dentists Registration Tribunal",
    "Meghalaya State Dental council",
    "Mizoram State Dentist Registration Tribunal",
    "Nagaland State Dental Council",
    "Orissa State Dental Council",
    "State Dental Council, Puducherry",
    "Punjab State Dental Council",
    "Rajasthan State Dental Council",
    "Sikkim Dental Registration Tribunal",
    "Tamil Nadu State Dental Council",
    "Telangana State Dental Council",
    "Tripura State Dental Council",
    "Uttarakhand Dentists Registration Tribunals",
    "Uttar Pradesh State Dental Council",
    "West Bengal State Dental Council",
    "Dental Council of India",
  ],
  "Ayurveda": [
    "Andhra Pradesh Board for Indian Medicine and Homoeopathy",
    "Council of Indian Medicine, Arunachal Pradesh",
    "Assam State Council of Indian Medicine",
    "Bihar State Council of Ayurvedic and Unani Medicine",
    "Chhattisgarh Board of Ayurvedic and Unani System of Medicine and Naturopathy",
    "Delhi Bhartiya Chikitsa Parishad",
    "Goa Council of Ayurvedic and other Allied Indian Systems of Medicine",
    "Gujarat Board of Ayurvedic & Unani Systems of Medicine",
    "Council of Indian Medicine, Haryana",
    "Board of Ayurvedic and Unani Systems of Medicine, Himachal Pradesh",
    "Board of Ayurvedic & Unani System of Medicine, Jammu and Kashmir",
    "Jharkhand State Ayush Medical Council",
    "The Karnataka Ayurvedic & Unani Practitioners Board",
    "Kerala State Medical Councils",
    "Madhya Pradesh Board of Ayurvedic and Unani Systems of Medicine and Naturopathy",
    "Maharashtra Council of Indian Medicine",
    "Orissa State Council of Ayurvedic Medicine",
    "Board of Ayurvedic & Unani Systems of Medicine, Punjab",
    "Board of Indian Medicine, Rajasthan",
    "Tamil Nadu Board of Indian Medicine, Madras",
    "Government of Telangana Board of Indian Medicine",
    "Bhartiya Chikitsa Parishad, Uttarakhand",
    "Bhartiya Chikitsa Parishad, Uttar Pradesh",
    "Paschim Banga Ayurved Parishad",
    "National Commission for Indian System of Medicine (erstwhile Central Council of Indian Medicine)"
  ],
  "Homeopathy": [
    "Andhra Pradesh Board for Indian Medicine and Homoeopathy",
    "Arunachal Pradesh Homoeopathic Council",
    "Board of Homoeopathic System of Medicine, Assam",
    "State Board of Homoeopathic Medicine, Bihar",
    "Homoeopathic system of Medicine, Chandigarh",
    "State Council of Homoeopathy, Chhattisgarh",
    "Board of Homoeopathic System of Medicine, Delhi",
    "The Goa Indian System of Medicine and Homoeopathy Council",
    "Council of Homoeopathic System of Medicine, Gujarat",
    "Council of Homoeopathic System of Medicine, Haryana",
    "Homoeopathic Medical Council, Himachal Pradesh",
    "Jammu and Kashmir Board of Homoeopathic System of Medicine",
    "Jharkhand State AYUSH Parishad",
    "Karnataka Board of Homoeopathic System of Medicine",
    "Kerala State Medical Councils",
    "Madhya Pradesh State Council of Homoeopathy",
    "Maharashtra Council of Homoeopathy",
    "Board of Homoeopathic Medicine, Meghalaya",
    "Mizoram State Council of Homoeopathy",
    "Board of Homoeopathic System of Medicine, Nagaland",
    "Odisha State Board of Homoeopathic Medicine",
    "Council of Homoeopathic System of Medicine, Punjab",
    "Rajasthan Homoeopathic Medical Board",
    "Tamil Nadu Homoeopathy Medical Council",
    "Government of Telangana Board of Indian Medicine",
    "Council of Homoeopathic Medicine, Tripura",
    "Homoeopathic Medicine Board, Uttarakhand",
    "Homoeopathic Medicine Board, Uttar Pradesh",
    "Council of Homoeopathic Medicine, West Bengal",
    "Central Council of Homoeopathy",
    "National Commission for Homoeopathy"
  ],
}