import React from "react";
// import "./customergrievance.css";

const CustomerGrievance = () => {
    return (
        <div className="customer-grievance-content">
            <div className="container return-refund-div-content" dangerouslySetInnerHTML={{
                __html: `<p><b>ABOUT THE POLICY</b></p>
          <p>The Customer Grievance Redressal Policy highlights Axaone Technologies Private Limited’s (“Company”, “HealthSy”, “Axaone”, “Our”, “Us”, “We”) policy towards redressing the customer’s (“You”, “Consumer”, “User”) grievances that might arise from purchase of goods and services on the Company's website or mobile applications.</p>
          <p>We believe that customer satisfaction and the trust that the consumers place on our brand “HealthSy” are some of the key factors that enables us to stride forward and grow. Similarly, we love to ensure that we reciprocate this love in every way possible. One of the ways in which we can reciprocate this through fair, easy and quick redressing of the grievances raised by you in the event of any unsatisfactory experiences that might arise from time to time. So, we kindly request you to refer to this policy for grievance resolving. This policy will act as a mechanism that will enable us to give you maximum satisfaction by solving your grievances in an effective and efficient manner.</p>
          <p>We would also like to remind the concerned stakeholders such as you that HealthSy is simply a technology platform that facilitates buying and selling process on the platform by connecting the sellers/retailers with the online consumers. The products purchased on our platform are owned and sold by third party sellers/retailers. Similarly, the services availed through our platform is also provided by third party individuals. The company does not have hold and ownership over the products and all product related grievances are directly addressed and responsibility of the concerned seller/retailer. However, we will assist you in getting them resolved through them (sellers/retailers) by adopting the best possible methods.</p>
          <p><b>PURPOSES AND OBJECTIVES OF THIS POLICY</b></p>
          <p>	<b>1. An effective mechanism:</b> We want our consumers not to be helpless with regards to the turnaround time taken to resolve a grievance, receive half answers, non-fulfillment of your grievances. The methods adopted by us for redressing consumer’s grievances will be effective an efficient.</p>
          <p>	<b>2.	Fairness and Equality:</b> We want to ensure that all are consumers are equal and that their grievances are redressed in a fair manner. </p>
          <p>	<b>3.	Promptness and Courtesy:</b> To ensure that the grievances, complaints and queries raised by you through our platform is responded with utmost courtesy. The turnaround time for a response to a grievance or complaint raised by you is within 24 hours from the time of receiving it. </p>
          <p>	<b>4.	Awareness:</b> The ultimate objective of this policy is to make our consumers aware of their rights and that this mechanism is available for them to solve their grievances.  </p>
          <p><b>METHODS OF GRIEVANCE REDRESSAL MECHANISM</b></p>
          <h2>	<b>1.	NEED SUPPORT:</b> This mechanism is available to the consumers on mobile application and the website. There is 12+ topics where each topic addresses several key issues surrounding that particular topic. These FAQs itself will be very handy in resolving your queries/grievances. To go to “Need Support” kindly login to your account in the app or website ---&gt; Go to “Need Support” from your account / profile page -----&gt; Select your Topic ------&gt; Select an Issue ------&gt; Adequate answers will be shown there. The topics ranges from “Medicine and Healthcare Orders related”, “General Queries”, “Online Doctor Consultation related”, “Payments related”, “Returns, Cancellations and Refunds related” and several other such topics.</h2>
          <p>	<b>2.	NEED MORE SUPPORT: </b> We are well aware that sometimes the FAQs will not be sufficient in resolving your queries/grievances to its fullest potential. Therefore, under every topic and under every issue related to that particular topic we have the next level of customer grievance redressal mechanism called the “Need More Support”. When you click onto the “Need More Support” option for any a particular issue, a popup with Call, Chat or Mail options will appear. In some cases, all three options (Call, Chat, Mail) to reach out to our customer support team will be available for you. When you opt for a telephonic call, a customer support agent will be in touch with you and help you in resolving your query or grievance. Similarly, if you opt for Chat, you will be connected to a customer support agent within 2-5 minutes. You can raise your concerns / grievances over chat with the agent who will try and solve your case in the best possible manner. Alternately, you can mail us at <a href="mailto:grievance-officer@healthsy.in" class="privacyMailNavigate p-0">grievance-officer@healthsy.in </a>with your queries / grievances and we will respond back within 24 hours of receiving your mail. </p>
          <p><b>3.	GRIEVANCE OFFICER: </b>  If by any chance your queries/grievances raised through the above methods don’t find you a response or if you are not satisfied with the responses given, you can reach out to our “Grievance Officer” Mr. Arul S. The “Grievance Officer” will be responsible for redressing consumer's grievances with accordance to the consumer grievance redressal mechanisms mentioned in the policy. To solve your queries / grievances contact the “Grievance Officer” at:</p>
          <p>a. Email: <a href="mailto:grievance-officer@healthsy.in" class="privacyMailNavigate p-0">grievance-officer@healthsy.in</a></p>
          <p>b. Mobile Number: 7603944039</p>
          <p>Post receiving your complaint/query/grievance over a telephonic call or through email, customer shall receive an acknowledgement from the grievance officer within 48 hours. The grievance officer will employ the best available methods in resolving your complaint/query/grievance within 15 days from the date of receiving the same. The contact numbers mentioned on this policy shall be functional from Monday-Saturday between 09:30 AM – 07:00 PM. Please note that on certain national and public holidays, the contact number(s) mentioned on this policy might not be functional.</p>
          <p><b>DISCLAIMER CLAUSE AND OTHER IMPORTANT POINTS</b></p>
          <p>1.	The HealthSy Customer Grievance Redressal Policy is formulated in correspondence to the existing and applicable laws and guidelines issued by the concerned authorities. </p>
          <p>2.	The company has the right to modify or change this policy in correspondence to the applicable laws and guidelines in order to give better customer support and customer satisfaction.</p>
          <p>3.	Beware of fraudulent calls/emails/messages /advertisements that might put you in an unpleasant situation. HealthSy or its employees will not ask for any confidential information such as your OTPs/CVV/Debit/Credit card PIN details. Under no circumstances you can reveal this information to anyone for your safety.</p>
          <p>4.	Sharing such confidential information to scammers, unauthorized people, imposters, phishers might put you under financial and psychological risks which the company will not be responsible in any manner. </p>
          <p>5.	Any complaint/query/grievance that is related to “Non-Returnable Products” are not covered under this policy. Kindly refer to the Return, Refund, and Cancellation Policy here.</p>
          <p>6.	In certain cases of grievance redressal, there might be delayed solutions for which the company has no say in but will assist in getting an assured solution from the sellers/retailers/payment gateways by adopting the best methods available. </p>
          <p>7. Compensation Clause : The user accepts and agrees that Axaone, it’s subsidiaries, brands or any of its partners will not be held liable for any kind of monetary, financial or other kinds of compensation in the event of any untoward incidents that is caused to the patient. The user accepts and agrees that Axaone and its brand HealthSy is purely a technology platform and an aggregator that is engaged in connecting the users to the network of qualified and licensed partners across the country if the user wants and is intended to avail the services or products listed on Axaone’s online platforms namely the HealthSy app and website. Axaone, its subsidiaries, brands, directors, shareholders or employees will not be held responsible or liable for any damage caused to the user in the event of any untoward incidents like injury, death, loss of any property, etc </p>`}}>
            </div>
        </div>
    );
}


export default CustomerGrievance;